---
- name: Install nginx package
  apt:
    name:
      - nginx
    state: present
    update_cache: true

- name: Copy Nginx config file
  ansbile.builtin.copy:
    - src: /opt/devops/Mini-Prj-1/config/default
    - dst: /etc/nginx/sites-enabled/default

- name: Restart Nginx Service
  ansible.builtin.service:
    name: nginx
    state: restarted