---
- name: Copy Files
  copy:
    src: /opt/devops/voting-system/vote-master
    dst: /opt/devops/voting-system
    directory_mode: yes

- name: Install Python dependencies
  apt:
    name:
      - python3-redis
      - python3-flask
      - gunicorn
    state: present
    update_cache: true

- name: Copy Runner Script
  copy:
    src: /opt/devops/Mini-Prj-1/runner/vote.sh
    dst: /opt/devops/Mini-Prj-1/runner/vote.sh

- name: Copy Service file
  copy:
    src: /opt/devops/Mini-Prj-1/service/vote.service
    dst: /etc/systemd/system

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart Vote Service
  ansible.builtin.systemd:
    name: vote
    state: restarted
    
